### ISSUE TITLE
No event log for successful launch of Agent Launcher bat file or Powershell script

### ISSUE THREAD

**Issue by AngryProgrammerInside** [AngryProgrammerInside/InstallAgent#14]
Documentation states there is a Exit Code 10 and Event in application log with a code 10

**Comment by Robby-Swartenbroekx** [comment]
Rechecked the code, that is in there now. You probably changed it (line 182 in the bat file), because in an older version I still had was a successfull exit as an error and now it is informational.
also documentation seems to be OK

**Comment by AngryProgrammerInside** [comment]
Yes, this one was fixed in commit 67139b36be8aaa0df829e298f6db668c7fe2b55d
